### ISSUE TITLE
Problem when trying to change pseudo_numbers 

### ISSUE THREAD

**Issue by sfias** [theochem/horton#103]
I've been playing with changing the pseudo_numbers of molecules, because this is useful to calculate the so-called 'alchemical' changes. Now, when I start from a xyz-file and try to change the nuclear charge (pseudo_numbers) of an atom like this: `mol.pseudo_numbers[0] = 0.90`, this doesn't work. I found that the ArrayTypeCheckDescriptor, when there is a default, like the numbers in this case, never sets the attribute. To solve this I used maybe the most absurd line of code I've ever written: `mol.pseudo_numbers = mol.pseudo_numbers`

to solve this, I would change the following code (at this point on line 83 of iodate.py)

    def __get__(self, obj, type=None):
        if obj is None:
            return self
        if self._default is not None and not hasattr(obj, '_' + self._name):
            return getattr(obj, '_' + self._default).astype(self._dtype)
        return getattr(obj, '_' + self._name)

to:

    def __get__(self, obj, type=None):
        if obj is None:
            return self
        if self._default is not None and not hasattr(obj, '_' + self._name):
            #I changed the next line, it works, but is it a good idea/desirable? 
            setattr(obj, '_' + self._name,(getattr(obj, '_' + self._default).astype(self._dtype)))
        return getattr(obj, '_' + self._name)

This works for my problem and the nosetests run fine, but I'm not sure this code is a good idea or desirable.

**Comment by tovrstra** [comment]
Oh, I remember we once discussed this. I'm too tired now but I'll look into this soon.

**Comment by tovrstra** [comment]
@sfias : what you suggest is indeed the proper way to solve this. Can you make a PR?

**Comment by tovrstra** [comment]
Fixed by merging #106.
