### ISSUE TITLE
trapdoor.py not working on mac?

### ISSUE THREAD

**Issue by sfias** [theochem/horton#107]
I run into problems when using `./tools/qa/test_all_twobranches.sh` on my mac. The problem is that, when following the installation as described in the documentation, coverage, pylint and pydocstyle aren't installed as command-line scripts, but have to be called as `python -m /pylint/pydocstyle`. Apparently a similar problem can or used to occur in Debian, where python-coverage is used. Would it be better or more general to use python -m coverage/pylint/pydocstyle instead?

**Comment by tovrstra** [comment]
Closing. See discussion in PR #108.
