### ISSUE TITLE
Literalinclude wrong: ../data/examples/hf_dft/rhf_water_dense.py in doc/user_hamiltonian_molecular.rst

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#13]
-    :lines: 18-25
    -    :caption: data/examples/hf_dft/rhf_water_dense.py, lines 18--25
    +    :lines: 22-29
    +    :caption: data/examples/hf_dft/rhf_water_dense.py, lines 22--29

**Comment by tovrstra** [comment]
Fix ready, waiting with PR until PR #26 is merged.

**Comment by matt-chan** [comment]
Merged into 2.0.1
