### ISSUE TITLE
Deprecate Ubuntu 14.04 support

### ISSUE THREAD

**Issue by matt-chan** [theochem/horton#153]
It looks like we can't support 14.04 anymore because the numpy in the repos is too old? 14.04 has 1.8.2, while all of the other distros use 1.11.x. I can't finish all the unit tests on buildkite with it. 

We could amend the code to use code compatible with the old numpy (only two violations from what I can see), but maybe that's a losing battle? It's technically their old LTS distribution, so there may still be users on it (including Travis? But I'm not sure why it's not breaking there)

If we want to deprecate it, we should update the docs and remove the setup.cfg for it.

**Comment by kimt33** [comment]
With pip, I have numpy 1.11.1 on my Windows Ubuntu. Is it possible to use pip on the builders?

**Comment by matt-chan** [comment]
Yes, but technically it's not good practice to be using pip. It's a fairly
reliable way to break your distro, since it installs things into the same
path as your package manager. I think if you use pip to install 1.11, then
if ubuntu makes a minor update to 1.8, it may overwrite your 1.11 and
you'll be back at 1.8. It's also possible for pip to overwrite the ubuntu
packages and then other ubuntu packages will have the wrong numpy version.
Pip is technically an out-of-repo package. In Fedora it's a little better
because RPM won't isn't supposed to overwrite files that have been modified
(meaning no 1.11 -> 1.8 changes) but all the system packages will still be
expecting 1.8 and they'll get 1.11 instead. If the API changes, then things
will break, often unexpectedly and/or silently. It's not a problem for me
to test with a pip package though, since docker instances have no
permanence.

One option is to install via pip into --user, but then you have a (less
severe) problem of trying to figure out which version of numpy you're
using. Not sure if we want to recommend users to do this, or just put a
blanket "we're not supporting this configuration" statement, and let them
figure stuff out themselves with pip.

**Comment by kimt33** [comment]
Hmm.. Any chance we can get pip (or w/e installer) to install onto a custom directory? If we put it inside horton and modify the __init__, we can get something like horton.depends.numpy. This way, there is no conflict between pip and the package manager.
Or maybe it's too complicated. We can just not support certain OS and if enough people complain about it we can put up a hacky solution.

**Comment by matt-chan** [comment]
Yes, pip supports this. You could tell it to put things into /opt for
example, and then add it to your PYTHONPATH, before running HORTON. ie

PYTHONPATH=/opt/numpy python horton_script.py

It's still rather complicated though. The --user solution is more elegant
and has nearly the same effect, but it's still prone to failure. If a user
doesn't know what an environmental variable is, or doesn't know how python
module resolution works, then it'll be super confusing. I'd recommend just
putting the instructions online (for say Win10 users) and saying it's a
completely unsupported version of Ubuntu. If it breaks, they need to know
how to fix it themselves?

**Comment by tovrstra** [comment]
I would recommend to use the `--user` option of pip, such that you do not need root permission to install newer packages locally. (This is also explained in the installation manual.) That will not interfere with the version installed on the distribution. Without the `--user` option, pip should normally install in `/usr/local/`, which is not touched by package managers either.

I would not work with `/opt`, because it is a non-default location. Then one has to modify `${PYTHONPATH}, which can be avoided. Python will look by default in certain subdirectories of ${HOME}/.local and /usr/local, which are also the default places where pip installs packages, with or without the `--user` option respectively.

I don't think this is really an issue, so I'm closing it. Feel free to reopen though.
