### ISSUE TITLE
Do not use `from horton import foo` internally

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#16]
Instead use `from horton.foo import foo`

**Comment by tovrstra** [comment]
It would also be good to detect such poor practices with QA scripts.

**Comment by tovrstra** [comment]
There is a QA trapdoor script for import conventions that counts the number of bad import lines.

**Comment by matt-chan** [comment]
I can make the changes to the current master

**Comment by tovrstra** [comment]
Also from `horton.grid import foo` should be avoided. Same for other horton subpackages. The script `tools/qa/trapdoor_import` should be improved to detect this.

**Comment by tovrstra** [comment]
Fixed by merging PR #55.
