### ISSUE TITLE
Some users get Cython error when Cythoning horton/gbasis/cext.pyx ('vector[float64_t] *' to 'vector[double] *)

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#182]
This is the error:

    horton/gbasis/cext.pyx:130:46: Cannot assign type 'vector[float64_t] *' to 'vector[double] *

which eventually breaks the compilation of the extension:

    "horton/gbasis/cext.cpp:1:2:error: #error Do not use this file, it is the result of a failed Cython compilation."

I'm not sure which Cython version is causing this problem.

**Comment by matt-chan** [comment]
Can we add some code to the setup.py script to output the versions of the
libraries we're linking against? This would help the reproducibility
project too.

**Comment by tovrstra** [comment]
Good idea. I did some basic testing but could not reproduce the error yet. Combinations tested (on Fedora 24):

- Cython 0.23.4 (rpm), with libint2-devel rpm
- Cython 0.24.1 (pip), with libint2-devel rpm
- Cython 0.23.4 (rpm), with libint2 installed in qaworkdir
- Cython 0.24.1 (pip), with libint2 installed in qaworkdir

**Comment by tovrstra** [comment]
The user reporting this problem was running Cython 0.24.

**Comment by tovrstra** [comment]
I can reproduce the problem with Cython 0.24. The bug is fixed in 0.24.1. See 

https://github.com/cython/cython/blob/master/CHANGES.rst

The following bug in 0.24 is probably the cause: "Assignments between identical C++ types that were declared with differently typedefed template types could fail."

We need to exclude 0.24 in the install instructions (and figure out which distributions are shipping this version).
