### ISSUE TITLE
Switch to openblas

### ISSUE THREAD

**Issue by matt-chan** [theochem/horton#189]
So since Ubuntu users get openblas, osx users take forever to build atlas, and Fedora users get an unoptimised version of atlas, I think maybe we should switch our dependency to openblas? I'm not sure how numpy linking will go though.

**Comment by matt-chan** [comment]
I'm trying to figure out what happens if we use atlas on numpy (Fedora linked that way) and openblas for HORTON. And what happens if you use openblas for both.

@tovrstra: thoughts?

**Comment by tczorro** [comment]
I found some fun parts. I actually compile Horton with atlas. But my numpy version is numpy +openblas. All the tests pass.
The problem for compiling Horton with only atlas is some files like horton/gbasis/cholesky.h require cblas.h which is only provided by ATLAS(at least on macos).

**Comment by tovrstra** [comment]
@tczorro : I believe openblas also has cblas.h, you just need to explain your computer where its sits using the CPATH variable. (See https://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html). Depending on your OS and local config, you may also have to install "the development package" of openblas. (See http://stackoverflow.com/questions/35544356/install-caffe-on-mac-error-fatal-error-cblas-h-file-not-found) You don't need this after compilation, which explains the result you get.

@matt-chan: There may be a problem when NumPy and HORTON both link dynamically to a different blas. I would expect name clash issues but since the API is the same, both will probably end up using just one instead of two different ones. (I'm not sure.)

**Comment by tczorro** [comment]
cblas.h should be in the lib. But Macport change it's name into cblas_openblas. I assume it just want to avoid naming confliction with atlas.
The solutions I can come up with are when compiling Horton changing the content of cholesky.py from cblas.h into cblas_openblas.h or switching to homebrew as the package manager.

**Comment by tczorro** [comment]
@tovrstra I think I found a bug. In the horton-2.0.1.tar.gz, there is no dependencies.json in the folder.

**Comment by matt-chan** [comment]
@tovrstra: So I can understand how that happens in a C++ program since they all share the same symbol table(?). But does the python interpreter handle libraries like that? Or are calls executed in separate subprocesses, etc? Because it seems really easy to have a case where one python package in PyPi is built with Atlas and another with openblas, and I'm surprised the CPython authors wouldn't foresee a situation like that arising.

**Comment by tczorro** [comment]
@matt-chan 
Just for openblas to replace atlas on Mac, it's complete viable. Tested with numpy +openblas, compiled with openblas and cblas_openblas.h. All the nosetests pass.

**Comment by tovrstra** [comment]
The Python interpreter loads python extensions, which are shared objects, dynamically. Linking with these is not done at compile time, so there is no risk for name clashes between different extensions. The extensions define most contents statically and list them in a method-table data structure that is given back to Python. See also this stackexchange question:

http://stackoverflow.com/questions/678254/what-should-i-do-if-two-libraries-provide-a-function-with-the-same-name-generati#

I'm not sure what will happen when two different extensions link dynamically to a different libraries with overlapping APIs? That seems to be a can of worms.

We may use numpy to find the BLAS/LAPACK it links to, and then use that as well. That may fail when the development files of these BLAS/LAPACK libraries are not installed. See for example:

http://stackoverflow.com/questions/9000164/how-to-check-blas-lapack-linkage-in-numpy-scipy

**Comment by tovrstra** [comment]
We should just get rid of the BLAS dependency. It is actually not needed in HORTON.
