### ISSUE TITLE
Mac install instructions need py27-readline

### ISSUE THREAD

**Issue by matt-chan** [theochem/horton#190]
Mac ports has a bug where py27-readline needs to be installed if you use python on terminal. We should add this to our install instructions.

See https://track.macports.org/ticket/48807

**Comment by tovrstra** [comment]
Can you fix the link? It seems broken.

**Comment by tovrstra** [comment]
@matt-chan : Can you fix the link? The URL seems invalid.

**Comment by matt-chan** [comment]
That's so weird. The link works if I type it in, but not if I click. 

https://trac.macports.org/ticket/48807

**Comment by tovrstra** [comment]
OK. I see. I would like to have a minimal solution. Does the installation of python with `+readline` also fix this? (That is easier to deal with in the documentation.)

**Comment by matt-chan** [comment]
Yup. That looks like a better solution
