### ISSUE TITLE
libxc version problem

### ISSUE THREAD

**Issue by tczorro** [theochem/horton#191]
@tovrstra  @matt-chan 
All this situation happened to my laptop.
MacOS 10.12

After updating libxc from libxc 2.1.2(2.2.2) to libxc 2.1.3(2.2.3), one test (horton.meanfield.test.test_libxc.test_dot_hessian_o3lyp_cs_polynomial) goes wrong all the time.

If I remove all the libxc from macport and only use the one from tools/qa, then following error message comes out when compiling horton,

/usr/bin/clang++ -bundle -undefined dynamic_lookup -isysroot / -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db48 build/temp.macosx-10.12-x86_64-2.7/horton/meanfield/cext.o -lxc -o /Users/Derrick/Documents/Project/horton_test/horton/meanfield/cext.so
ld: library not found for -lxc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit status 1

I guess -lxc have something to do with library path or something similar.
Since the newest version for libxc is 2.1.3. We should figure out where is the problem.

**Comment by tczorro** [comment]
So I think the libxc problem should be related to cext.so

**Comment by tovrstra** [comment]
The `-lxc` instructs the compiler to link with Libxc dynamically. Could there be a setup.cfg file in the root of your source tree that instructs `setup.py` to link to Libxc dynamically? For more details, see http://theochem.github.io/horton/2.0.1/user_download_and_install_setup_cfg.html

**Comment by tczorro** [comment]
I set setup.cfg to the one in qaworkdir, but it still gives the error.
libxc 2.2.2 is installed through ./toos/qa/install_libxc-2.2.2.sh
Set CPATH to that dir still doesn't work.
For the path problem, macport can handle that.
So my concern is the new libxc(2.1.3 or 2.2.3) version leads to an error and I guess it has something to do with horton/meanfield/cext.so
But I don't know much C so I can't check too further.

**Comment by tovrstra** [comment]
I'm not too familiar with OSX, so this is hard to fix remotely.

This week, I installed the latest development version of HORTON on a mac, but with many dependencies installed with homebrew instead of macports. In that case, I had to build libxc and libint with the `install_*.sh` scripts in `tools/qa`. All went fine without any setup.cfg in the root of the source directory. Building against the openblas (from homebrew) also worked.

Can you check with your local OSX guru, to see how this can be fixed? It looks to me like a linker problem. These are generally no fun, certainly not on OSX.

**Comment by tovrstra** [comment]
It seems that aggressive compiler optimization flags can cause LibXC to give wrong results. This is not mentioned in the documentation. I guess you were compiling the HORTON extension with a LibXC version other than the one compiled by `./toos/qa/install_libxc-2.2.2.sh`.

I'm going to close this. If the problem persists, feel free to reopen.
