### ISSUE TITLE
Libxc version in new Fedora repo

### ISSUE THREAD

**Issue by kimt33** [theochem/horton#224]
Fedora (25) has now updated Libxc to version 3.0.0, which means that the documentation for building HORTON in Linux is now out of date. We can just change the documentation so that libxc gets installed through `install_deps_extra.sh` or specify the version of libxc.

**Comment by kimt33** [comment]
Related: #40.

**Comment by tovrstra** [comment]
This is a matter of documentation of the install process. I'll take care of this.
