### ISSUE TITLE
Install fails on Fedora Server 25

### ISSUE THREAD

**Issue by HenriqueCSJ** [theochem/horton#231]
Following step-by-step the instructions provided by the documentation, installation fails on Fedora Server 25:
```
[henrique@site horton-2.0.1]$ ./setup.py install --user
MACHINE=Linux-Fedora-25-x86_64
Traceback (most recent call last):
  File "./setup.py", line 285, in <module>
    with open('dependencies.json') as f:
IOError: [Errno 2] No such file or directory: 'dependencies.json'
```

**Comment by tovrstra** [comment]
This is a known problem: some files are missing from the archive. We should make a 2.0.2 release to fix this. I'll prepare something, so you can give it a try.

**Comment by tovrstra** [comment]
This should work now with release 2.1.0 (and 2.0.2).

**Comment by tovrstra** [comment]
P.S. If you still run into problems, feel free to open an new issue.
