### ISSUE TITLE
Which new module for Atoms-in-Molecules analysis

### ISSUE THREAD

**Issue by bannanc** [theochem/horton#289]
Hello! 

I am a psi4 user and have been looking for a way to calculate atomic charges from psi4 output (since only Mulliken and Lowdin are available in psi4 itself). I was excited to find Horton as an option for expanding our choices of atomic charges. However, all of the other tools I'm using are in python3. I'm having a difficult time figuring out which of the Horton3 modules has the Atoms-in-Molecules analysis. Specifically, examples of how to calculate Hirshfeld charges from psi4 output (or molden files) would be greatly appreciated. 

Thank you in advance for the help.

**Comment by tovrstra** [comment]
We're (slowly) porting everything over to new packages, which are written in Python 3. There are no plans to rewrite the old HORTON for Python 3. If you want to use it, I'd suggest to install it in a Python 2 conda environment. The following conda package should work fine: https://anaconda.org/pyqc/horton

**Comment by bannanc** [comment]
Hi @tovrstra, thank you for your quick response. Just to make sure I'm understanding the current state of things, the Atoms-in-Molecules analysis isn't in any of the new packages yet, correct? I understood from the documentation that you were refactoring the code. I know how much work that is and appreciate it taking time. I just wanted to make sure that I didn't miss something in looking at your newer repositories. 

The specific problem I'm working on is adding Hirshfeld charges to my company's existing workflows. I could use a python2 environment locally, but that won't work for me in the bigger picture since our software no longer supports python2.  

Thank you for your time!

**Comment by tovrstra** [comment]
Yes, you understood correctly. Sorry for the disappointment. 

Are you specifically interested in *Hirshfeld* charges, i.e. not the iterative method or any newer developments? The 1977 Hirshfeld method may not be very useful for modeling electrostatic interactions in biological systems. We would be very happy to make the newer methods easily available to people working on the OFF initiative. That is definitely high on my wish list.

**Comment by bannanc** [comment]
Oh, I'm sorry for the confusion, the newer methods I think are preferred. My expertise is in other areas so I'm still learning about the best models for electrostatics. I know the OFF initiative would be very interested in a way to use those methods with psi4. 

I've actually graduated so I'm not working directly with OpenFF anymore. I'm at OpenEye Scientific Software now as an Applications Scientist . We use psi4 as a quantum chemistry package which has a fairly limited number of options for atomic charges. I've been looking for open source options we could add to expand the number of atomic charges we can make accessible on our platform.

**Comment by tovrstra** [comment]
@bannanc Thanks for the background. I'll keep this issue open, so I can come back here to give an update as soon as we have something usable. When we published the MBIS method, we did some comparison with a selection of available methods, see [10.1021/acs.jctc.6b00456](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00456).

If you want to get the output from PSI4 into HORTON2, you need to write out a Molden file in PSI4, as explained here: http://www.psicode.org/psi4manual/master/molden.html There were some changes in the 1.3 release of PSI4 to improve the numerical precision in the Molden files, which I'd recommend. These Molden files can be read by the `horton-wpart.py` script.

**Comment by bannanc** [comment]
Thanks so much for your help @tovrstra! I will see if I can at least test with the Horton2 package for now.

**Comment by tovrstra** [comment]
I believe this one can be closed as per #291 .
