### ISSUE TITLE
The ordering of P orbitals for pure Gaussian functions

### ISSUE THREAD

**Issue by yingxingcheng** [theochem/horton#298]
According to the implementation of integrals, when spherical or pure Gaussian functions are used, Horton (3 or 2) and Psi4 (version=1.0.x-1.7.x) should give the same integrals. However, it is not always true, e.g., oxygen pairs with cc-pVDZ basis set. 

I'm not sure if this a potential issue, but I found the ordering of `p` angular momentum for pure Gaussian functions is still `x y z` instead of `z x y` by default: 

https://github.com/theochem/horton/blob/3a5adfeac6eba42a8cc468ff16a4b0b9a34ee69e/horton/gbasis/iobas.py#L35-L41

Are there some specific reasons for this?

**Comment by PaulWAyers** [comment]
@tovrstra or @kimt33 any thoughts on this? I know that PySCF uses the same convention *except* that it uses $x,y,z$ order for the p's instead of the (more sensible) order from [wikipedia](https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics) ($y,z,x$).

**Comment by yingxingcheng** [comment]
The conventional order used in Horton (version=2.1.1) is [here](https://theochem.github.io/horton/2.1.1/tech_ref_gaussian_basis.html#pure-or-harmonic-basis-functions). But, it is a little bit different from the implementation mentioned above.

**Comment by yingxingcheng** [comment]
I guess because Gaussian and Molden also use the order " $x$ $y$ $z$ ", and no one cares about its order. ;)

**Comment by PaulWAyers** [comment]
@yingxingcheng did you get this sorted out? I assume that @tovrstra can help you with this.

**Comment by yingxingcheng** [comment]
I've received confirmation from David, as it is a common practice in other software such as Gaussian.

**Comment by tovrstra** [comment]
As far as I remember, Gaussian does not have "pure p" functions. I believe p functions are written out in Cartesian order, even when doing a calculation with pure basis functions. If you have an example showing the opposite, it would be good to attach a wavefunction file and explain how it was obtained. (A small example would be Ideal, so it can be used in a unit test.)
