### ISSUE TITLE
Parsing coverage output is not robust

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#35]
The format of the screen output depends on the version over Coverage.py, so we'd better not rely on it.  The XML output is not great either because it provides only line-by-line information with way too much detail. It is probably also possible to directly interact with the coverage API to extract the information of interest.

**Comment by tovrstra** [comment]
The coverage API turned to be less convenient than expected. Parsing the XML as way easier and should work across all versions of coverage.py.

**Comment by matt-chan** [comment]
PR #38 merged in
