### ISSUE TITLE
Additional Gaussian integrals

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#57]
We should add integrals for forces and multipole moments. I believe the code is already lingering in some branches but it should just be dusted a little.

**Comment by tovrstra** [comment]
@sfias : I vaguely remember you had implemented integrals for multipole moments (and forces?) Anything you have is welcome. It would be nice to rebase before merging but we can help with that if needed.

**Comment by sfias** [comment]
I'm on it. I rebased and I'm cleaning the code, documenting it and writing some small unit tests...

**Comment by tovrstra** [comment]
Great! Thanks. Looking forward to it.

**Comment by tovrstra** [comment]
@fhqgfss @PaulWAyers 

Yilin, I noticed some of your comments on Stijn's code in my mail box but they do not appear on github anymore because they refer to outdated commits. I'll just quote your points below:

1. Regarding check of validity of xyz argument of `GB2MomentIntegral` constructor: I think it's OK to leave it as none negative, when the sum is 0, it's just overlap integral or in another word zero-order multipole moment. but this won't cause trouble to the code I think

2. Regarding `compute_multipole_moment` method: Is the center have a default value [0., 0., 0.]
also I'm not sure if it is better to add center of mass and center of charge as choice for the center option since sometimes physical community prefer using them?

**Comment by tovrstra** [comment]
Short replies to the points above:

1. Only non-negative powers of x, y and z are allowed in the latest version of Stijn's PR (the one that got merged).

2. There is no default value for the center. Having _clever_ options like center of mass is not desirable because it would decrease code modularity. It would imply that the Gaussian integral code knows about the positions and the masses of the nuclei, which is not essential for the computation of integrals. That goes against the principle of separation of concerns. When the NA integrals are computed, the positions and charges of the nuclei are just passed as method arguments. These don't have to be nuclear positions of the molecule. They can also be QM/MM charges or one is free to do weird things like alchemical exchange. Such flexibility is possible because we don't store nuclear info in the basis set object.

**Comment by fhqgfss** [comment]
sorry, I mean the overall can be also 0 when all x, y, z are zero. And
thanks for the comment on the value of center problem

**Comment by PaulWAyers** [comment]
I see Toon's point on this. The "center issue" does not belong with the integrals, but in the "code around the integrals." (I.e., it is an issue related to how the integrals are used, rather than the integrals themselves.) The same sort of philosophy occurs elsewhere in HORTON, probably. E.g., DIIS should be generic (not tied to HF/DFT) so that it could be used for coupled-cluster and other problems like that, too.

**Comment by tovrstra** [comment]
I think this can be closed. If anyone has implemented operators for the derivatives of the Hartree potential w.r.t. (nuclear) Cartesian coordinates, please let me know.

**Comment by PaulWAyers** [comment]
If there is interest in the derivatives of the Hartree potential I think it can be constructed relatively easily (maybe not quickly) using the Poisson-solver already in HORTON for the transition-densities.
