### ISSUE TITLE
Newer version of cppcheck and doxygen on Travis

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#72]
The ubuntu 12.04 versions are so old that they don't detect certain problems. There is probably a ppa to fix this.

**Comment by tovrstra** [comment]
There is no ppa that can be used to install a newer version of cppcheck and doxygen. Building doxygen from scratch takes too long, so I'm dropping that idea. Building the latest cppcheck is still worth the trouble. (It is a relatively compact code.)

**Comment by matt-chan** [comment]
Hmm also don't forget that this LTS is ending soon. I think it's going to
be cut in 2017.04?

Some of these problems may just go away.

**Comment by tovrstra** [comment]
There are more recent build environments. The one based on Trusty is still in beta:
https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
Even Trusty is not very recent, e.g. only has cppcheck 1.61. :((

**Comment by tovrstra** [comment]
Fixed by merging PR #77.
