### ISSUE TITLE
Drop support for older distros (ubuntu 12.04 and fedora 21)

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#75]
I've tried to install on Ubuntu 12.04 but it is a nightmare to get it working. Given it's nearing end-of-life, it makes little sense to keep supporting it with draconian instructions for backporting recent packages.

I have not tried to install on fedora 21 but given it is past its end of life, we can safely drop it and stop worrying.

**Comment by tovrstra** [comment]
@matt-chan Would you agree?

**Comment by matt-chan** [comment]
Yep. I'm all for it.

I don't think people should be trying to use 12.04 LTS anyways... It's way
too close to EOL.

**Comment by tovrstra** [comment]
Fixed by merge PR #79.
