### ISSUE TITLE
Test 2.0.1 on mac

### ISSUE THREAD

**Issue by matt-chan** [theochem/horton#89]
Give to @tczorro

**Comment by tczorro** [comment]
[test_result_local_build_dp.txt](https://github.com/theochem/horton/files/309751/test_result_local_build_dp.txt)

**Comment by tovrstra** [comment]
Thanks! The nosetests output looks pretty awful but it is actually quite ok. Can you try running the tests again after doing the following? http://theochem.github.io/horton/tech_dev_git.html#additional-steps-required-to-build-the-development-version-of-horton

**Comment by matt-chan** [comment]
Ahh... This is probably why Stijn didn't have any problems.

**Comment by sfias** [comment]
Tests on my MacBook Pro (Retina, 15-inch, Early 2013) ran fine, both on OSX 10.10.5 and after updating to OSX 10.11.5

**Comment by matt-chan** [comment]
Okay. All good. Thanks you guys!

**Comment by tovrstra** [comment]
Good, I'll close it then. (If new OSX related issues appear, fixes are still welcome of course.)
